version: 2

sources:
  - name: staging
    database: de-zoomcamp-412201
    schema: trips_data_all

      
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata